# Generated by Django 5.2.11 on 2026-02-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epstein_ui', '0012_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
