# Generated by Django 5.2.11 on 2026-02-16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("epstein_ui", "0013_add_comment_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="annotation",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="annotation_comment",
        ),
        migrations.DeleteModel(
            name="ArrowItem",
        ),
        migrations.DeleteModel(
            name="CommentVote",
        ),
        migrations.DeleteModel(
            name="TextItem",
        ),
        migrations.DeleteModel(
            name="AnnotationComment",
        ),
        migrations.DeleteModel(
            name="AnnotationVote",
        ),
        migrations.DeleteModel(
            name="Annotation",
        ),
    ]
